version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 3165:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    container_name: yvm-nginx
  yvm:
    build: .
    volumes:
      - ./classes:/var/www/html/classes
      - ./notes:/var/www/html/notes
    hostname: yvm
    container_name: yvm-service
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
